version: '3.8'

services:
  backend:
    build:
      context: /home/fabianosf/Documents/projeto/asbjj_django/backend
      dockerfile: /home/fabianosf/Documents/projeto/docker/Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - /home/fabianosf/Documents/projeto/asbjj_django/backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build:
      context: /home/fabianosf/Documents/projeto/asbjj_reactjs
      dockerfile: /home/fabianosf/Documents/projeto/docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - /home/fabianosf/Documents/projeto/asbjj_reactjs:/app
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
